# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/telemetry/battery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/telemetry/battery.proto',
  package='lynk.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bmsg/telemetry/battery.proto\x12\x0elynk.telemetry\":\n\x07\x42\x61ttery\x12\x0f\n\x07voltage\x18\x01 \x01(\x02\x12\x0f\n\x07\x63urrent\x18\x02 \x01(\x02\x12\r\n\x05level\x18\x03 \x01(\x02\x62\x06proto3')
)




_BATTERY = _descriptor.Descriptor(
  name='Battery',
  full_name='lynk.telemetry.Battery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='voltage', full_name='lynk.telemetry.Battery.voltage', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current', full_name='lynk.telemetry.Battery.current', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='lynk.telemetry.Battery.level', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['Battery'] = _BATTERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Battery = _reflection.GeneratedProtocolMessageType('Battery', (_message.Message,), dict(
  DESCRIPTOR = _BATTERY,
  __module__ = 'msg.telemetry.battery_pb2'
  # @@protoc_insertion_point(class_scope:lynk.telemetry.Battery)
  ))
_sym_db.RegisterMessage(Battery)


# @@protoc_insertion_point(module_scope)
