syntax = "proto3";
package lynk.command;

enum GimbalMode {
  GIMBAL_MODE_FOLLOW = 0;
  GIMBAL_MODE_LOCK = 1;
  GIMBAL_MODE_FOLLOW_LOCK = 2;
}

enum StreamType {
  STREAM_TYPE_RGB = 0;
  STREAM_TYPE_THERMAL = 1;
}

enum WhiteBalanceMode {
  WHITE_BALANCE_AWB_AUTO = 0;
  WHITE_BALANCE_AWB_NIGHT = 1;
  WHITE_BALANCE_AWB_INCANDESCENT = 2;
  WHITE_BALANCE_AWB_FLUORESCENT = 3;
  WHITE_BALANCE_AWB_WARM_FLUORESCENT = 4;
  WHITE_BALANCE_AWB_DAYLIGHT = 5;
  WHITE_BALANCE_AWB_CLOUDY = 6;
  WHITE_BALANCE_AWB_TWILIGHT = 7;
  WHITE_BALANCE_AWB_SHADE = 8;
}

enum FalseColorPalette {
  FALSE_COLOR_PALETTE_UNKNOWN = 0;
  FALSE_COLOR_PALETTE_WHITE_HOT = 1;
  FALSE_COLOR_PALETTE_SEPIA = 3;
  FALSE_COLOR_PALETTE_IRONBOW = 4;
  FALSE_COLOR_PALETTE_RAINBOW = 5;
  FALSE_COLOR_PALETTE_NIGHT = 6;
  FALSE_COLOR_PALETTE_AURORA = 7;
  FALSE_COLOR_PALETTE_RED_HOT = 8;
  FALSE_COLOR_PALETTE_JUNGLE = 9;
  FALSE_COLOR_PALETTE_MEDICAL = 10;
  FALSE_COLOR_PALETTE_BLACK_HOT = 11;
  FALSE_COLOR_PALETTE_GLORY_HOT = 12;
}

enum DigitalZoomLevel {
  DIGITAL_ZOOM_UNKNOWN = 0;
  DIGITAL_ZOOM_1X = 1;
  DIGITAL_ZOOM_2X = 2;
  DIGITAL_ZOOM_3X = 3;
  DIGITAL_ZOOM_4X = 4;
  DIGITAL_ZOOM_IN = 10;
  DIGITAL_ZOOM_OUT = 11;
}
