# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/mavlink/mavlink_tunnel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/mavlink/mavlink_tunnel.proto',
  package='lynk.mavlink',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n msg/mavlink/mavlink_tunnel.proto\x12\x0clynk.mavlink\"_\n\rMavlinkTunnel\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x11\n\tsystem_id\x18\x02 \x01(\r\x12\x14\n\x0c\x63omponent_id\x18\x03 \x01(\r\x12\x14\n\x0ctimestamp_us\x18\x04 \x01(\x04\x62\x06proto3')
)




_MAVLINKTUNNEL = _descriptor.Descriptor(
  name='MavlinkTunnel',
  full_name='lynk.mavlink.MavlinkTunnel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='lynk.mavlink.MavlinkTunnel.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='system_id', full_name='lynk.mavlink.MavlinkTunnel.system_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='component_id', full_name='lynk.mavlink.MavlinkTunnel.component_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_us', full_name='lynk.mavlink.MavlinkTunnel.timestamp_us', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['MavlinkTunnel'] = _MAVLINKTUNNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MavlinkTunnel = _reflection.GeneratedProtocolMessageType('MavlinkTunnel', (_message.Message,), dict(
  DESCRIPTOR = _MAVLINKTUNNEL,
  __module__ = 'msg.mavlink.mavlink_tunnel_pb2'
  # @@protoc_insertion_point(class_scope:lynk.mavlink.MavlinkTunnel)
  ))
_sym_db.RegisterMessage(MavlinkTunnel)


# @@protoc_insertion_point(module_scope)
