syntax = "proto3";
package lynk.telemetry;

import "msg/telemetry/gps.proto";
import "msg/telemetry/imu.proto";
import "msg/telemetry/battery.proto";
import "msg/telemetry/heartbeat.proto";
import "msg/telemetry/barometer.proto";
import "msg/telemetry/ping.proto";

message TelemetryEnvelope {
  // Telemetry ID'yi payload tag ile esliyoruz.
  uint32 tlm_id = 255;
  
  oneof payload {
    Gps gps = 1;
    Imu imu = 2;
    Battery battery = 3;
    Heartbeat heartbeat = 4;
    Barometer barometer = 5;
    Ping ping = 6;
  }
}
