syntax = "proto3";
package lynk.telemetry;

import "msg/telemetry/gps.proto";
import "msg/telemetry/attitude.proto";
import "msg/telemetry/battery.proto";
import "msg/telemetry/state.proto";
import "msg/telemetry/vfr_hud.proto";
import "msg/telemetry/heartbeat.proto";

message TelemetryEnvelope {
  // Telemetry ID'yi payload tag ile esliyoruz.
  uint32 tlm_id = 255;
  
  oneof payload {
    Gps gps = 1;
    Attitude attitude = 2;
    Battery battery = 3;
    State state = 4;
    VfrHud vfr_hud = 5;
    Heartbeat heartbeat = 6;
  }
}
