# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/ack/ack_error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/ack/ack_error.proto',
  package='lynk.ack',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17msg/ack/ack_error.proto\x12\x08lynk.ack\"\x17\n\x05\x45rror\x12\x0e\n\x06\x63md_id\x18\x01 \x01(\rb\x06proto3')
)




_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='lynk.ack.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_id', full_name='lynk.ack.Error.cmd_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['Error'] = _ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'msg.ack.ack_error_pb2'
  # @@protoc_insertion_point(class_scope:lynk.ack.Error)
  ))
_sym_db.RegisterMessage(Error)


# @@protoc_insertion_point(module_scope)
