# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/camera_take_photo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/camera_take_photo.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#msg/command/camera_take_photo.proto\x12\x0clynk.command\"\x11\n\x0f\x43\x61meraTakePhotob\x06proto3')
)




_CAMERATAKEPHOTO = _descriptor.Descriptor(
  name='CameraTakePhoto',
  full_name='lynk.command.CameraTakePhoto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['CameraTakePhoto'] = _CAMERATAKEPHOTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraTakePhoto = _reflection.GeneratedProtocolMessageType('CameraTakePhoto', (_message.Message,), dict(
  DESCRIPTOR = _CAMERATAKEPHOTO,
  __module__ = 'msg.command.camera_take_photo_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.CameraTakePhoto)
  ))
_sym_db.RegisterMessage(CameraTakePhoto)


# @@protoc_insertion_point(module_scope)
