# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/camera_record_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/camera_record_control.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'msg/command/camera_record_control.proto\x12\x0clynk.command\"%\n\x13\x43\x61meraRecordControl\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x62\x06proto3')
)




_CAMERARECORDCONTROL = _descriptor.Descriptor(
  name='CameraRecordControl',
  full_name='lynk.command.CameraRecordControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable', full_name='lynk.command.CameraRecordControl.enable', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['CameraRecordControl'] = _CAMERARECORDCONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraRecordControl = _reflection.GeneratedProtocolMessageType('CameraRecordControl', (_message.Message,), dict(
  DESCRIPTOR = _CAMERARECORDCONTROL,
  __module__ = 'msg.command.camera_record_control_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.CameraRecordControl)
  ))
_sym_db.RegisterMessage(CameraRecordControl)


# @@protoc_insertion_point(module_scope)
