# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/camera_set_white_balance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.command import command_enums_pb2 as msg_dot_command_dot_command__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/camera_set_white_balance.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n*msg/command/camera_set_white_balance.proto\x12\x0clynk.command\x1a\x1fmsg/command/command_enums.proto\"E\n\x15\x43\x61meraSetWhiteBalance\x12,\n\x04mode\x18\x01 \x01(\x0e\x32\x1e.lynk.command.WhiteBalanceModeb\x06proto3')
  ,
  dependencies=[msg_dot_command_dot_command__enums__pb2.DESCRIPTOR,])




_CAMERASETWHITEBALANCE = _descriptor.Descriptor(
  name='CameraSetWhiteBalance',
  full_name='lynk.command.CameraSetWhiteBalance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='lynk.command.CameraSetWhiteBalance.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=162,
)

_CAMERASETWHITEBALANCE.fields_by_name['mode'].enum_type = msg_dot_command_dot_command__enums__pb2._WHITEBALANCEMODE
DESCRIPTOR.message_types_by_name['CameraSetWhiteBalance'] = _CAMERASETWHITEBALANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraSetWhiteBalance = _reflection.GeneratedProtocolMessageType('CameraSetWhiteBalance', (_message.Message,), dict(
  DESCRIPTOR = _CAMERASETWHITEBALANCE,
  __module__ = 'msg.command.camera_set_white_balance_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.CameraSetWhiteBalance)
  ))
_sym_db.RegisterMessage(CameraSetWhiteBalance)


# @@protoc_insertion_point(module_scope)
