# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/camera_stream_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.command import command_enums_pb2 as msg_dot_command_dot_command__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/camera_stream_control.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'msg/command/camera_stream_control.proto\x12\x0clynk.command\x1a\x1fmsg/command/command_enums.proto\"T\n\x13\x43\x61meraStreamControl\x12-\n\x0bstream_type\x18\x01 \x01(\x0e\x32\x18.lynk.command.StreamType\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[msg_dot_command_dot_command__enums__pb2.DESCRIPTOR,])




_CAMERASTREAMCONTROL = _descriptor.Descriptor(
  name='CameraStreamControl',
  full_name='lynk.command.CameraStreamControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_type', full_name='lynk.command.CameraStreamControl.stream_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable', full_name='lynk.command.CameraStreamControl.enable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=174,
)

_CAMERASTREAMCONTROL.fields_by_name['stream_type'].enum_type = msg_dot_command_dot_command__enums__pb2._STREAMTYPE
DESCRIPTOR.message_types_by_name['CameraStreamControl'] = _CAMERASTREAMCONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraStreamControl = _reflection.GeneratedProtocolMessageType('CameraStreamControl', (_message.Message,), dict(
  DESCRIPTOR = _CAMERASTREAMCONTROL,
  __module__ = 'msg.command.camera_stream_control_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.CameraStreamControl)
  ))
_sym_db.RegisterMessage(CameraStreamControl)


# @@protoc_insertion_point(module_scope)
