# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/camera_set_digital_zoom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.command import command_enums_pb2 as msg_dot_command_dot_command__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/camera_set_digital_zoom.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)msg/command/camera_set_digital_zoom.proto\x12\x0clynk.command\x1a\x1fmsg/command/command_enums.proto\"E\n\x14\x43\x61meraSetDigitalZoom\x12-\n\x05level\x18\x01 \x01(\x0e\x32\x1e.lynk.command.DigitalZoomLevelb\x06proto3')
  ,
  dependencies=[msg_dot_command_dot_command__enums__pb2.DESCRIPTOR,])




_CAMERASETDIGITALZOOM = _descriptor.Descriptor(
  name='CameraSetDigitalZoom',
  full_name='lynk.command.CameraSetDigitalZoom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='lynk.command.CameraSetDigitalZoom.level', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=161,
)

_CAMERASETDIGITALZOOM.fields_by_name['level'].enum_type = msg_dot_command_dot_command__enums__pb2._DIGITALZOOMLEVEL
DESCRIPTOR.message_types_by_name['CameraSetDigitalZoom'] = _CAMERASETDIGITALZOOM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraSetDigitalZoom = _reflection.GeneratedProtocolMessageType('CameraSetDigitalZoom', (_message.Message,), dict(
  DESCRIPTOR = _CAMERASETDIGITALZOOM,
  __module__ = 'msg.command.camera_set_digital_zoom_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.CameraSetDigitalZoom)
  ))
_sym_db.RegisterMessage(CameraSetDigitalZoom)


# @@protoc_insertion_point(module_scope)
