# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/command_enums.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/command_enums.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fmsg/command/command_enums.proto\x12\x0clynk.command*W\n\nGimbalMode\x12\x16\n\x12GIMBAL_MODE_FOLLOW\x10\x00\x12\x14\n\x10GIMBAL_MODE_LOCK\x10\x01\x12\x1b\n\x17GIMBAL_MODE_FOLLOW_LOCK\x10\x02*:\n\nStreamType\x12\x13\n\x0fSTREAM_TYPE_RGB\x10\x00\x12\x17\n\x13STREAM_TYPE_THERMAL\x10\x01*\xb5\x02\n\x10WhiteBalanceMode\x12\x1a\n\x16WHITE_BALANCE_AWB_AUTO\x10\x00\x12\x1b\n\x17WHITE_BALANCE_AWB_NIGHT\x10\x01\x12\"\n\x1eWHITE_BALANCE_AWB_INCANDESCENT\x10\x02\x12!\n\x1dWHITE_BALANCE_AWB_FLUORESCENT\x10\x03\x12&\n\"WHITE_BALANCE_AWB_WARM_FLUORESCENT\x10\x04\x12\x1e\n\x1aWHITE_BALANCE_AWB_DAYLIGHT\x10\x05\x12\x1c\n\x18WHITE_BALANCE_AWB_CLOUDY\x10\x06\x12\x1e\n\x1aWHITE_BALANCE_AWB_TWILIGHT\x10\x07\x12\x1b\n\x17WHITE_BALANCE_AWB_SHADE\x10\x08*\x9f\x03\n\x11\x46\x61lseColorPalette\x12\x1f\n\x1b\x46\x41LSE_COLOR_PALETTE_UNKNOWN\x10\x00\x12!\n\x1d\x46\x41LSE_COLOR_PALETTE_WHITE_HOT\x10\x01\x12\x1d\n\x19\x46\x41LSE_COLOR_PALETTE_SEPIA\x10\x03\x12\x1f\n\x1b\x46\x41LSE_COLOR_PALETTE_IRONBOW\x10\x04\x12\x1f\n\x1b\x46\x41LSE_COLOR_PALETTE_RAINBOW\x10\x05\x12\x1d\n\x19\x46\x41LSE_COLOR_PALETTE_NIGHT\x10\x06\x12\x1e\n\x1a\x46\x41LSE_COLOR_PALETTE_AURORA\x10\x07\x12\x1f\n\x1b\x46\x41LSE_COLOR_PALETTE_RED_HOT\x10\x08\x12\x1e\n\x1a\x46\x41LSE_COLOR_PALETTE_JUNGLE\x10\t\x12\x1f\n\x1b\x46\x41LSE_COLOR_PALETTE_MEDICAL\x10\n\x12!\n\x1d\x46\x41LSE_COLOR_PALETTE_BLACK_HOT\x10\x0b\x12!\n\x1d\x46\x41LSE_COLOR_PALETTE_GLORY_HOT\x10\x0c*\xab\x01\n\x10\x44igitalZoomLevel\x12\x18\n\x14\x44IGITAL_ZOOM_UNKNOWN\x10\x00\x12\x13\n\x0f\x44IGITAL_ZOOM_1X\x10\x01\x12\x13\n\x0f\x44IGITAL_ZOOM_2X\x10\x02\x12\x13\n\x0f\x44IGITAL_ZOOM_3X\x10\x03\x12\x13\n\x0f\x44IGITAL_ZOOM_4X\x10\x04\x12\x13\n\x0f\x44IGITAL_ZOOM_IN\x10\n\x12\x14\n\x10\x44IGITAL_ZOOM_OUT\x10\x0b*y\n\x17TrajectoryAlgorithmType\x12 \n\x1cTRAJECTORY_ALGORITHM_UNKNOWN\x10\x00\x12\x1d\n\x19TRAJECTORY_ALGORITHM_SIDE\x10\x01\x12\x1d\n\x19TRAJECTORY_ALGORITHM_TAIL\x10\x02\x62\x06proto3')
)

_GIMBALMODE = _descriptor.EnumDescriptor(
  name='GimbalMode',
  full_name='lynk.command.GimbalMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GIMBAL_MODE_FOLLOW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GIMBAL_MODE_LOCK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GIMBAL_MODE_FOLLOW_LOCK', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=49,
  serialized_end=136,
)
_sym_db.RegisterEnumDescriptor(_GIMBALMODE)

GimbalMode = enum_type_wrapper.EnumTypeWrapper(_GIMBALMODE)
_STREAMTYPE = _descriptor.EnumDescriptor(
  name='StreamType',
  full_name='lynk.command.StreamType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STREAM_TYPE_RGB', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STREAM_TYPE_THERMAL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=138,
  serialized_end=196,
)
_sym_db.RegisterEnumDescriptor(_STREAMTYPE)

StreamType = enum_type_wrapper.EnumTypeWrapper(_STREAMTYPE)
_WHITEBALANCEMODE = _descriptor.EnumDescriptor(
  name='WhiteBalanceMode',
  full_name='lynk.command.WhiteBalanceMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WHITE_BALANCE_AWB_AUTO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_BALANCE_AWB_NIGHT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_BALANCE_AWB_INCANDESCENT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_BALANCE_AWB_FLUORESCENT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_BALANCE_AWB_WARM_FLUORESCENT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_BALANCE_AWB_DAYLIGHT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_BALANCE_AWB_CLOUDY', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_BALANCE_AWB_TWILIGHT', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_BALANCE_AWB_SHADE', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=199,
  serialized_end=508,
)
_sym_db.RegisterEnumDescriptor(_WHITEBALANCEMODE)

WhiteBalanceMode = enum_type_wrapper.EnumTypeWrapper(_WHITEBALANCEMODE)
_FALSECOLORPALETTE = _descriptor.EnumDescriptor(
  name='FalseColorPalette',
  full_name='lynk.command.FalseColorPalette',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_WHITE_HOT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_SEPIA', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_IRONBOW', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_RAINBOW', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_NIGHT', index=5, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_AURORA', index=6, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_RED_HOT', index=7, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_JUNGLE', index=8, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_MEDICAL', index=9, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_BLACK_HOT', index=10, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE_COLOR_PALETTE_GLORY_HOT', index=11, number=12,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=511,
  serialized_end=926,
)
_sym_db.RegisterEnumDescriptor(_FALSECOLORPALETTE)

FalseColorPalette = enum_type_wrapper.EnumTypeWrapper(_FALSECOLORPALETTE)
_DIGITALZOOMLEVEL = _descriptor.EnumDescriptor(
  name='DigitalZoomLevel',
  full_name='lynk.command.DigitalZoomLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_ZOOM_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_ZOOM_1X', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_ZOOM_2X', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_ZOOM_3X', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_ZOOM_4X', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_ZOOM_IN', index=5, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_ZOOM_OUT', index=6, number=11,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=929,
  serialized_end=1100,
)
_sym_db.RegisterEnumDescriptor(_DIGITALZOOMLEVEL)

DigitalZoomLevel = enum_type_wrapper.EnumTypeWrapper(_DIGITALZOOMLEVEL)
_TRAJECTORYALGORITHMTYPE = _descriptor.EnumDescriptor(
  name='TrajectoryAlgorithmType',
  full_name='lynk.command.TrajectoryAlgorithmType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRAJECTORY_ALGORITHM_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAJECTORY_ALGORITHM_SIDE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAJECTORY_ALGORITHM_TAIL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1102,
  serialized_end=1223,
)
_sym_db.RegisterEnumDescriptor(_TRAJECTORYALGORITHMTYPE)

TrajectoryAlgorithmType = enum_type_wrapper.EnumTypeWrapper(_TRAJECTORYALGORITHMTYPE)
GIMBAL_MODE_FOLLOW = 0
GIMBAL_MODE_LOCK = 1
GIMBAL_MODE_FOLLOW_LOCK = 2
STREAM_TYPE_RGB = 0
STREAM_TYPE_THERMAL = 1
WHITE_BALANCE_AWB_AUTO = 0
WHITE_BALANCE_AWB_NIGHT = 1
WHITE_BALANCE_AWB_INCANDESCENT = 2
WHITE_BALANCE_AWB_FLUORESCENT = 3
WHITE_BALANCE_AWB_WARM_FLUORESCENT = 4
WHITE_BALANCE_AWB_DAYLIGHT = 5
WHITE_BALANCE_AWB_CLOUDY = 6
WHITE_BALANCE_AWB_TWILIGHT = 7
WHITE_BALANCE_AWB_SHADE = 8
FALSE_COLOR_PALETTE_UNKNOWN = 0
FALSE_COLOR_PALETTE_WHITE_HOT = 1
FALSE_COLOR_PALETTE_SEPIA = 3
FALSE_COLOR_PALETTE_IRONBOW = 4
FALSE_COLOR_PALETTE_RAINBOW = 5
FALSE_COLOR_PALETTE_NIGHT = 6
FALSE_COLOR_PALETTE_AURORA = 7
FALSE_COLOR_PALETTE_RED_HOT = 8
FALSE_COLOR_PALETTE_JUNGLE = 9
FALSE_COLOR_PALETTE_MEDICAL = 10
FALSE_COLOR_PALETTE_BLACK_HOT = 11
FALSE_COLOR_PALETTE_GLORY_HOT = 12
DIGITAL_ZOOM_UNKNOWN = 0
DIGITAL_ZOOM_1X = 1
DIGITAL_ZOOM_2X = 2
DIGITAL_ZOOM_3X = 3
DIGITAL_ZOOM_4X = 4
DIGITAL_ZOOM_IN = 10
DIGITAL_ZOOM_OUT = 11
TRAJECTORY_ALGORITHM_UNKNOWN = 0
TRAJECTORY_ALGORITHM_SIDE = 1
TRAJECTORY_ALGORITHM_TAIL = 2


DESCRIPTOR.enum_types_by_name['GimbalMode'] = _GIMBALMODE
DESCRIPTOR.enum_types_by_name['StreamType'] = _STREAMTYPE
DESCRIPTOR.enum_types_by_name['WhiteBalanceMode'] = _WHITEBALANCEMODE
DESCRIPTOR.enum_types_by_name['FalseColorPalette'] = _FALSECOLORPALETTE
DESCRIPTOR.enum_types_by_name['DigitalZoomLevel'] = _DIGITALZOOMLEVEL
DESCRIPTOR.enum_types_by_name['TrajectoryAlgorithmType'] = _TRAJECTORYALGORITHMTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
