# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/flight_set_heading.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/flight_set_heading.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$msg/command/flight_set_heading.proto\x12\x0clynk.command\"?\n\x10\x46lightSetHeading\x12\x0c\n\x04mode\x18\x01 \x01(\r\x12\x0f\n\x07yaw_deg\x18\x02 \x01(\x02\x12\x0c\n\x04turn\x18\x03 \x01(\x05\x62\x06proto3')
)




_FLIGHTSETHEADING = _descriptor.Descriptor(
  name='FlightSetHeading',
  full_name='lynk.command.FlightSetHeading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='lynk.command.FlightSetHeading.mode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw_deg', full_name='lynk.command.FlightSetHeading.yaw_deg', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turn', full_name='lynk.command.FlightSetHeading.turn', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['FlightSetHeading'] = _FLIGHTSETHEADING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlightSetHeading = _reflection.GeneratedProtocolMessageType('FlightSetHeading', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHTSETHEADING,
  __module__ = 'msg.command.flight_set_heading_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.FlightSetHeading)
  ))
_sym_db.RegisterMessage(FlightSetHeading)


# @@protoc_insertion_point(module_scope)
