# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/flight_goto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/flight_goto.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dmsg/command/flight_goto.proto\x12\x0clynk.command\"D\n\nFlightGoto\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x03 \x01(\x02\x12\x0f\n\x07\x61lt_ref\x18\x04 \x01(\rb\x06proto3')
)




_FLIGHTGOTO = _descriptor.Descriptor(
  name='FlightGoto',
  full_name='lynk.command.FlightGoto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='lynk.command.FlightGoto.lat', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lon', full_name='lynk.command.FlightGoto.lon', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt', full_name='lynk.command.FlightGoto.alt', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt_ref', full_name='lynk.command.FlightGoto.alt_ref', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['FlightGoto'] = _FLIGHTGOTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlightGoto = _reflection.GeneratedProtocolMessageType('FlightGoto', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHTGOTO,
  __module__ = 'msg.command.flight_goto_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.FlightGoto)
  ))
_sym_db.RegisterMessage(FlightGoto)


# @@protoc_insertion_point(module_scope)
