# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/flight_set_home.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/flight_set_home.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!msg/command/flight_set_home.proto\x12\x0clynk.command\">\n\rFlightSetHome\x12\x13\n\x0buse_current\x18\x01 \x01(\x08\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\x62\x06proto3')
)




_FLIGHTSETHOME = _descriptor.Descriptor(
  name='FlightSetHome',
  full_name='lynk.command.FlightSetHome',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_current', full_name='lynk.command.FlightSetHome.use_current', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='lynk.command.FlightSetHome.lat', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lon', full_name='lynk.command.FlightSetHome.lon', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['FlightSetHome'] = _FLIGHTSETHOME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlightSetHome = _reflection.GeneratedProtocolMessageType('FlightSetHome', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHTSETHOME,
  __module__ = 'msg.command.flight_set_home_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.FlightSetHome)
  ))
_sym_db.RegisterMessage(FlightSetHome)


# @@protoc_insertion_point(module_scope)
