# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/flight_set_roi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/flight_set_roi.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n msg/command/flight_set_roi.proto\x12\x0clynk.command\"I\n\x0c\x46lightSetRoi\x12\x10\n\x08roi_mode\x18\x01 \x01(\r\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\x12\r\n\x05\x61lt_m\x18\x04 \x01(\x02\x62\x06proto3')
)




_FLIGHTSETROI = _descriptor.Descriptor(
  name='FlightSetRoi',
  full_name='lynk.command.FlightSetRoi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roi_mode', full_name='lynk.command.FlightSetRoi.roi_mode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='lynk.command.FlightSetRoi.lat', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lon', full_name='lynk.command.FlightSetRoi.lon', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt_m', full_name='lynk.command.FlightSetRoi.alt_m', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['FlightSetRoi'] = _FLIGHTSETROI
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlightSetRoi = _reflection.GeneratedProtocolMessageType('FlightSetRoi', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHTSETROI,
  __module__ = 'msg.command.flight_set_roi_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.FlightSetRoi)
  ))
_sym_db.RegisterMessage(FlightSetRoi)


# @@protoc_insertion_point(module_scope)
