# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/gimbal_set_attitude.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/gimbal_set_attitude.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%msg/command/gimbal_set_attitude.proto\x12\x0clynk.command\"X\n\x11GimbalSetAttitude\x12\x0f\n\x07yaw_deg\x18\x01 \x01(\x02\x12\x11\n\tpitch_deg\x18\x02 \x01(\x02\x12\x10\n\x08roll_deg\x18\x03 \x01(\x02\x12\r\n\x05speed\x18\x04 \x01(\rb\x06proto3')
)




_GIMBALSETATTITUDE = _descriptor.Descriptor(
  name='GimbalSetAttitude',
  full_name='lynk.command.GimbalSetAttitude',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='yaw_deg', full_name='lynk.command.GimbalSetAttitude.yaw_deg', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch_deg', full_name='lynk.command.GimbalSetAttitude.pitch_deg', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll_deg', full_name='lynk.command.GimbalSetAttitude.roll_deg', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='lynk.command.GimbalSetAttitude.speed', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['GimbalSetAttitude'] = _GIMBALSETATTITUDE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GimbalSetAttitude = _reflection.GeneratedProtocolMessageType('GimbalSetAttitude', (_message.Message,), dict(
  DESCRIPTOR = _GIMBALSETATTITUDE,
  __module__ = 'msg.command.gimbal_set_attitude_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.GimbalSetAttitude)
  ))
_sym_db.RegisterMessage(GimbalSetAttitude)


# @@protoc_insertion_point(module_scope)
