# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/gimbal_set_mode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.command import command_enums_pb2 as msg_dot_command_dot_command__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/gimbal_set_mode.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!msg/command/gimbal_set_mode.proto\x12\x0clynk.command\x1a\x1fmsg/command/command_enums.proto\"7\n\rGimbalSetMode\x12&\n\x04mode\x18\x01 \x01(\x0e\x32\x18.lynk.command.GimbalModeb\x06proto3')
  ,
  dependencies=[msg_dot_command_dot_command__enums__pb2.DESCRIPTOR,])




_GIMBALSETMODE = _descriptor.Descriptor(
  name='GimbalSetMode',
  full_name='lynk.command.GimbalSetMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='lynk.command.GimbalSetMode.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=139,
)

_GIMBALSETMODE.fields_by_name['mode'].enum_type = msg_dot_command_dot_command__enums__pb2._GIMBALMODE
DESCRIPTOR.message_types_by_name['GimbalSetMode'] = _GIMBALSETMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GimbalSetMode = _reflection.GeneratedProtocolMessageType('GimbalSetMode', (_message.Message,), dict(
  DESCRIPTOR = _GIMBALSETMODE,
  __module__ = 'msg.command.gimbal_set_mode_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.GimbalSetMode)
  ))
_sym_db.RegisterMessage(GimbalSetMode)


# @@protoc_insertion_point(module_scope)
