# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/gimbal_set_velocity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/gimbal_set_velocity.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%msg/command/gimbal_set_velocity.proto\x12\x0clynk.command\"X\n\x11GimbalSetVelocity\x12\x14\n\x0cyaw_rate_dps\x18\x01 \x01(\x02\x12\x16\n\x0epitch_rate_dps\x18\x02 \x01(\x02\x12\x15\n\rroll_rate_dps\x18\x03 \x01(\x02\x62\x06proto3')
)




_GIMBALSETVELOCITY = _descriptor.Descriptor(
  name='GimbalSetVelocity',
  full_name='lynk.command.GimbalSetVelocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='yaw_rate_dps', full_name='lynk.command.GimbalSetVelocity.yaw_rate_dps', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch_rate_dps', full_name='lynk.command.GimbalSetVelocity.pitch_rate_dps', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll_rate_dps', full_name='lynk.command.GimbalSetVelocity.roll_rate_dps', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['GimbalSetVelocity'] = _GIMBALSETVELOCITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GimbalSetVelocity = _reflection.GeneratedProtocolMessageType('GimbalSetVelocity', (_message.Message,), dict(
  DESCRIPTOR = _GIMBALSETVELOCITY,
  __module__ = 'msg.command.gimbal_set_velocity_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.GimbalSetVelocity)
  ))
_sym_db.RegisterMessage(GimbalSetVelocity)


# @@protoc_insertion_point(module_scope)
