# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/gimbal_calibrate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/gimbal_calibrate.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"msg/command/gimbal_calibrate.proto\x12\x0clynk.command\"+\n\x0fGimbalCalibrate\x12\x18\n\x10\x63\x61libration_type\x18\x01 \x01(\rb\x06proto3')
)




_GIMBALCALIBRATE = _descriptor.Descriptor(
  name='GimbalCalibrate',
  full_name='lynk.command.GimbalCalibrate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='calibration_type', full_name='lynk.command.GimbalCalibrate.calibration_type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['GimbalCalibrate'] = _GIMBALCALIBRATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GimbalCalibrate = _reflection.GeneratedProtocolMessageType('GimbalCalibrate', (_message.Message,), dict(
  DESCRIPTOR = _GIMBALCALIBRATE,
  __module__ = 'msg.command.gimbal_calibrate_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.GimbalCalibrate)
  ))
_sym_db.RegisterMessage(GimbalCalibrate)


# @@protoc_insertion_point(module_scope)
