# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/gimbal_stop.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/gimbal_stop.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dmsg/command/gimbal_stop.proto\x12\x0clynk.command\"\x0c\n\nGimbalStopb\x06proto3')
)




_GIMBALSTOP = _descriptor.Descriptor(
  name='GimbalStop',
  full_name='lynk.command.GimbalStop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['GimbalStop'] = _GIMBALSTOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GimbalStop = _reflection.GeneratedProtocolMessageType('GimbalStop', (_message.Message,), dict(
  DESCRIPTOR = _GIMBALSTOP,
  __module__ = 'msg.command.gimbal_stop_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.GimbalStop)
  ))
_sym_db.RegisterMessage(GimbalStop)


# @@protoc_insertion_point(module_scope)
