# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/gimbal_track_target_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.command import command_enums_pb2 as msg_dot_command_dot_command__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/gimbal_track_target_control.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n-msg/command/gimbal_track_target_control.proto\x12\x0clynk.command\x1a\x1fmsg/command/command_enums.proto\"\x88\x01\n\x18GimbalTrackTargetControl\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12,\n\nvideo_type\x18\x02 \x01(\x0e\x32\x18.lynk.command.StreamType\x12\n\n\x02x0\x18\x03 \x01(\r\x12\n\n\x02y0\x18\x04 \x01(\r\x12\n\n\x02x1\x18\x05 \x01(\r\x12\n\n\x02y1\x18\x06 \x01(\rb\x06proto3')
  ,
  dependencies=[msg_dot_command_dot_command__enums__pb2.DESCRIPTOR,])




_GIMBALTRACKTARGETCONTROL = _descriptor.Descriptor(
  name='GimbalTrackTargetControl',
  full_name='lynk.command.GimbalTrackTargetControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable', full_name='lynk.command.GimbalTrackTargetControl.enable', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_type', full_name='lynk.command.GimbalTrackTargetControl.video_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x0', full_name='lynk.command.GimbalTrackTargetControl.x0', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y0', full_name='lynk.command.GimbalTrackTargetControl.y0', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x1', full_name='lynk.command.GimbalTrackTargetControl.x1', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y1', full_name='lynk.command.GimbalTrackTargetControl.y1', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=233,
)

_GIMBALTRACKTARGETCONTROL.fields_by_name['video_type'].enum_type = msg_dot_command_dot_command__enums__pb2._STREAMTYPE
DESCRIPTOR.message_types_by_name['GimbalTrackTargetControl'] = _GIMBALTRACKTARGETCONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GimbalTrackTargetControl = _reflection.GeneratedProtocolMessageType('GimbalTrackTargetControl', (_message.Message,), dict(
  DESCRIPTOR = _GIMBALTRACKTARGETCONTROL,
  __module__ = 'msg.command.gimbal_track_target_control_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.GimbalTrackTargetControl)
  ))
_sym_db.RegisterMessage(GimbalTrackTargetControl)


# @@protoc_insertion_point(module_scope)
