# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/gimbal_get_sd_capacity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/gimbal_get_sd_capacity.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(msg/command/gimbal_get_sd_capacity.proto\x12\x0clynk.command\"\x15\n\x13GimbalGetSdCapacityb\x06proto3')
)




_GIMBALGETSDCAPACITY = _descriptor.Descriptor(
  name='GimbalGetSdCapacity',
  full_name='lynk.command.GimbalGetSdCapacity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['GimbalGetSdCapacity'] = _GIMBALGETSDCAPACITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GimbalGetSdCapacity = _reflection.GeneratedProtocolMessageType('GimbalGetSdCapacity', (_message.Message,), dict(
  DESCRIPTOR = _GIMBALGETSDCAPACITY,
  __module__ = 'msg.command.gimbal_get_sd_capacity_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.GimbalGetSdCapacity)
  ))
_sym_db.RegisterMessage(GimbalGetSdCapacity)


# @@protoc_insertion_point(module_scope)
