# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/mission_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/mission_control.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!msg/command/mission_control.proto\x12\x0clynk.command\"\x1e\n\x0eMissionControl\x12\x0c\n\x04json\x18\x01 \x01(\tb\x06proto3')
)




_MISSIONCONTROL = _descriptor.Descriptor(
  name='MissionControl',
  full_name='lynk.command.MissionControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json', full_name='lynk.command.MissionControl.json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['MissionControl'] = _MISSIONCONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MissionControl = _reflection.GeneratedProtocolMessageType('MissionControl', (_message.Message,), dict(
  DESCRIPTOR = _MISSIONCONTROL,
  __module__ = 'msg.command.mission_control_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.MissionControl)
  ))
_sym_db.RegisterMessage(MissionControl)


# @@protoc_insertion_point(module_scope)
