# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/swarm_set_spacing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/swarm_set_spacing.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#msg/command/swarm_set_spacing.proto\x12\x0clynk.command\")\n\x0fSwarmSetSpacing\x12\x16\n\x0espacing_offset\x18\x01 \x01(\x01\x62\x06proto3')
)




_SWARMSETSPACING = _descriptor.Descriptor(
  name='SwarmSetSpacing',
  full_name='lynk.command.SwarmSetSpacing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spacing_offset', full_name='lynk.command.SwarmSetSpacing.spacing_offset', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['SwarmSetSpacing'] = _SWARMSETSPACING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwarmSetSpacing = _reflection.GeneratedProtocolMessageType('SwarmSetSpacing', (_message.Message,), dict(
  DESCRIPTOR = _SWARMSETSPACING,
  __module__ = 'msg.command.swarm_set_spacing_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.SwarmSetSpacing)
  ))
_sym_db.RegisterMessage(SwarmSetSpacing)


# @@protoc_insertion_point(module_scope)
