# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/swarm_set_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/swarm_set_status.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"msg/command/swarm_set_status.proto\x12\x0clynk.command\x1a\x0cnanopb.proto\"\'\n\x0eSwarmSetStatus\x12\x15\n\x06status\x18\x01 \x01(\tB\x05\x92?\x02\x08 b\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_SWARMSETSTATUS = _descriptor.Descriptor(
  name='SwarmSetStatus',
  full_name='lynk.command.SwarmSetStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='lynk.command.SwarmSetStatus.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\010 '), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['SwarmSetStatus'] = _SWARMSETSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwarmSetStatus = _reflection.GeneratedProtocolMessageType('SwarmSetStatus', (_message.Message,), dict(
  DESCRIPTOR = _SWARMSETSTATUS,
  __module__ = 'msg.command.swarm_set_status_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.SwarmSetStatus)
  ))
_sym_db.RegisterMessage(SwarmSetStatus)


_SWARMSETSTATUS.fields_by_name['status']._options = None
# @@protoc_insertion_point(module_scope)
