# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/swarm_set_formation_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/swarm_set_formation_type.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n*msg/command/swarm_set_formation_type.proto\x12\x0clynk.command\x1a\x0cnanopb.proto\"6\n\x15SwarmSetFormationType\x12\x1d\n\x0e\x66ormation_type\x18\x01 \x01(\tB\x05\x92?\x02\x08 b\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_SWARMSETFORMATIONTYPE = _descriptor.Descriptor(
  name='SwarmSetFormationType',
  full_name='lynk.command.SwarmSetFormationType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='formation_type', full_name='lynk.command.SwarmSetFormationType.formation_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\010 '), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['SwarmSetFormationType'] = _SWARMSETFORMATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwarmSetFormationType = _reflection.GeneratedProtocolMessageType('SwarmSetFormationType', (_message.Message,), dict(
  DESCRIPTOR = _SWARMSETFORMATIONTYPE,
  __module__ = 'msg.command.swarm_set_formation_type_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.SwarmSetFormationType)
  ))
_sym_db.RegisterMessage(SwarmSetFormationType)


_SWARMSETFORMATIONTYPE.fields_by_name['formation_type']._options = None
# @@protoc_insertion_point(module_scope)
