# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/thermal_set_false_color.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.command import command_enums_pb2 as msg_dot_command_dot_command__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/thermal_set_false_color.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)msg/command/thermal_set_false_color.proto\x12\x0clynk.command\x1a\x1fmsg/command/command_enums.proto\"H\n\x14ThermalSetFalseColor\x12\x30\n\x07palette\x18\x01 \x01(\x0e\x32\x1f.lynk.command.FalseColorPaletteb\x06proto3')
  ,
  dependencies=[msg_dot_command_dot_command__enums__pb2.DESCRIPTOR,])




_THERMALSETFALSECOLOR = _descriptor.Descriptor(
  name='ThermalSetFalseColor',
  full_name='lynk.command.ThermalSetFalseColor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='palette', full_name='lynk.command.ThermalSetFalseColor.palette', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=164,
)

_THERMALSETFALSECOLOR.fields_by_name['palette'].enum_type = msg_dot_command_dot_command__enums__pb2._FALSECOLORPALETTE
DESCRIPTOR.message_types_by_name['ThermalSetFalseColor'] = _THERMALSETFALSECOLOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThermalSetFalseColor = _reflection.GeneratedProtocolMessageType('ThermalSetFalseColor', (_message.Message,), dict(
  DESCRIPTOR = _THERMALSETFALSECOLOR,
  __module__ = 'msg.command.thermal_set_false_color_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.ThermalSetFalseColor)
  ))
_sym_db.RegisterMessage(ThermalSetFalseColor)


# @@protoc_insertion_point(module_scope)
