# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/telemetry/attitude.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/telemetry/attitude.proto',
  package='lynk.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cmsg/telemetry/attitude.proto\x12\x0elynk.telemetry\"V\n\x08\x41ttitude\x12\x10\n\x08roll_deg\x18\x01 \x01(\x02\x12\x11\n\tpitch_deg\x18\x02 \x01(\x02\x12\x0f\n\x07yaw_deg\x18\x03 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x04\x62\x06proto3')
)




_ATTITUDE = _descriptor.Descriptor(
  name='Attitude',
  full_name='lynk.telemetry.Attitude',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll_deg', full_name='lynk.telemetry.Attitude.roll_deg', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch_deg', full_name='lynk.telemetry.Attitude.pitch_deg', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw_deg', full_name='lynk.telemetry.Attitude.yaw_deg', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_ms', full_name='lynk.telemetry.Attitude.timestamp_ms', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['Attitude'] = _ATTITUDE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Attitude = _reflection.GeneratedProtocolMessageType('Attitude', (_message.Message,), dict(
  DESCRIPTOR = _ATTITUDE,
  __module__ = 'msg.telemetry.attitude_pb2'
  # @@protoc_insertion_point(class_scope:lynk.telemetry.Attitude)
  ))
_sym_db.RegisterMessage(Attitude)


# @@protoc_insertion_point(module_scope)
