# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/telemetry/barometer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/telemetry/barometer.proto',
  package='lynk.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dmsg/telemetry/barometer.proto\x12\x0elynk.telemetry\"T\n\tBarometer\x12\x16\n\x0evertical_speed\x18\x01 \x01(\x02\x12\x14\n\x0cground_speed\x18\x02 \x01(\x02\x12\x19\n\x11\x61ltitude_relative\x18\x03 \x01(\x02\x62\x06proto3')
)




_BAROMETER = _descriptor.Descriptor(
  name='Barometer',
  full_name='lynk.telemetry.Barometer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertical_speed', full_name='lynk.telemetry.Barometer.vertical_speed', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ground_speed', full_name='lynk.telemetry.Barometer.ground_speed', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude_relative', full_name='lynk.telemetry.Barometer.altitude_relative', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['Barometer'] = _BAROMETER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Barometer = _reflection.GeneratedProtocolMessageType('Barometer', (_message.Message,), dict(
  DESCRIPTOR = _BAROMETER,
  __module__ = 'msg.telemetry.barometer_pb2'
  # @@protoc_insertion_point(class_scope:lynk.telemetry.Barometer)
  ))
_sym_db.RegisterMessage(Barometer)


# @@protoc_insertion_point(module_scope)
