# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/telemetry/ping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/telemetry/ping.proto',
  package='lynk.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18msg/telemetry/ping.proto\x12\x0elynk.telemetry\"\x18\n\x04Ping\x12\x10\n\x08sequence\x18\x01 \x01(\rb\x06proto3')
)




_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='lynk.telemetry.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='lynk.telemetry.Ping.sequence', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['Ping'] = _PING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'msg.telemetry.ping_pb2'
  # @@protoc_insertion_point(class_scope:lynk.telemetry.Ping)
  ))
_sym_db.RegisterMessage(Ping)


# @@protoc_insertion_point(module_scope)
