# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/telemetry/state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/telemetry/state.proto',
  package='lynk.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19msg/telemetry/state.proto\x12\x0elynk.telemetry\"P\n\x05State\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\x10\n\x08is_armed\x18\x02 \x01(\x08\x12\x11\n\tconnected\x18\x03 \x01(\x08\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x04\x62\x06proto3')
)




_STATE = _descriptor.Descriptor(
  name='State',
  full_name='lynk.telemetry.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='lynk.telemetry.State.mode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_armed', full_name='lynk.telemetry.State.is_armed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connected', full_name='lynk.telemetry.State.connected', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_ms', full_name='lynk.telemetry.State.timestamp_ms', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(
  DESCRIPTOR = _STATE,
  __module__ = 'msg.telemetry.state_pb2'
  # @@protoc_insertion_point(class_scope:lynk.telemetry.State)
  ))
_sym_db.RegisterMessage(State)


# @@protoc_insertion_point(module_scope)
