# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/telemetry/vfr_hud.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/telemetry/vfr_hud.proto',
  package='lynk.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bmsg/telemetry/vfr_hud.proto\x12\x0elynk.telemetry\"\x93\x01\n\x06VfrHud\x12\x13\n\x0b\x61irspeed_ms\x18\x01 \x01(\x02\x12\x16\n\x0egroundspeed_ms\x18\x02 \x01(\x02\x12\x13\n\x0bheading_deg\x18\x03 \x01(\x02\x12\x10\n\x08throttle\x18\x04 \x01(\x02\x12\r\n\x05\x61lt_m\x18\x05 \x01(\x02\x12\x10\n\x08\x63limb_ms\x18\x06 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x07 \x01(\x04\x62\x06proto3')
)




_VFRHUD = _descriptor.Descriptor(
  name='VfrHud',
  full_name='lynk.telemetry.VfrHud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='airspeed_ms', full_name='lynk.telemetry.VfrHud.airspeed_ms', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groundspeed_ms', full_name='lynk.telemetry.VfrHud.groundspeed_ms', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading_deg', full_name='lynk.telemetry.VfrHud.heading_deg', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throttle', full_name='lynk.telemetry.VfrHud.throttle', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt_m', full_name='lynk.telemetry.VfrHud.alt_m', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='climb_ms', full_name='lynk.telemetry.VfrHud.climb_ms', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_ms', full_name='lynk.telemetry.VfrHud.timestamp_ms', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=195,
)

DESCRIPTOR.message_types_by_name['VfrHud'] = _VFRHUD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VfrHud = _reflection.GeneratedProtocolMessageType('VfrHud', (_message.Message,), dict(
  DESCRIPTOR = _VFRHUD,
  __module__ = 'msg.telemetry.vfr_hud_pb2'
  # @@protoc_insertion_point(class_scope:lynk.telemetry.VfrHud)
  ))
_sym_db.RegisterMessage(VfrHud)


# @@protoc_insertion_point(module_scope)
