vehicle:
  id: 4
  team_id: 1
  type: COPTER
protocol:
  start_byte: 84
  start_byte_2: 199
  version: 2
  compression_enabled: true
  compression_threshold: 128
interface:
  comm_type: UDP
uart:
  port: /dev/ttyUSB2
  baudrate: 57600
  timeout: 1
udp:
  local_ip: 0.0.0.0
  local_port: 5001
  remote_ip: 239.1.2.3
  remote_port: 5001
  idle_sleep_sec: 0.0002
  rcvbuf_bytes: 16777216
  rx_queue_size: 30
logging:
  enabled: true
  level: INFO
  clear_on_start: true
  write_to_file: true
security:
  enabled: true
  key: '9999999999999999999999999999999999999999999999999999999999999999'
relay:
  enabled: false
  max_hops: 2
  delay_ms: 50
