# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/flight_takeoff.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/flight_takeoff.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n msg/command/flight_takeoff.proto\x12\x0clynk.command\":\n\rFlightTakeoff\x12\x12\n\naltitude_m\x18\x01 \x01(\x02\x12\x15\n\rmin_pitch_deg\x18\x02 \x01(\x02\x62\x06proto3')
)




_FLIGHTTAKEOFF = _descriptor.Descriptor(
  name='FlightTakeoff',
  full_name='lynk.command.FlightTakeoff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='altitude_m', full_name='lynk.command.FlightTakeoff.altitude_m', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_pitch_deg', full_name='lynk.command.FlightTakeoff.min_pitch_deg', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['FlightTakeoff'] = _FLIGHTTAKEOFF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlightTakeoff = _reflection.GeneratedProtocolMessageType('FlightTakeoff', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHTTAKEOFF,
  __module__ = 'msg.command.flight_takeoff_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.FlightTakeoff)
  ))
_sym_db.RegisterMessage(FlightTakeoff)


# @@protoc_insertion_point(module_scope)
