# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/flight_set_speed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/flight_set_speed.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"msg/command/flight_set_speed.proto\x12\x0clynk.command\"2\n\x0e\x46lightSetSpeed\x12\x11\n\tspeed_mps\x18\x01 \x01(\x02\x12\r\n\x05scope\x18\x02 \x01(\rb\x06proto3')
)




_FLIGHTSETSPEED = _descriptor.Descriptor(
  name='FlightSetSpeed',
  full_name='lynk.command.FlightSetSpeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed_mps', full_name='lynk.command.FlightSetSpeed.speed_mps', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scope', full_name='lynk.command.FlightSetSpeed.scope', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['FlightSetSpeed'] = _FLIGHTSETSPEED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlightSetSpeed = _reflection.GeneratedProtocolMessageType('FlightSetSpeed', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHTSETSPEED,
  __module__ = 'msg.command.flight_set_speed_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.FlightSetSpeed)
  ))
_sym_db.RegisterMessage(FlightSetSpeed)


# @@protoc_insertion_point(module_scope)
