# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/flight_arming.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/flight_arming.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fmsg/command/flight_arming.proto\x12\x0clynk.command\"*\n\x0c\x46lightArming\x12\x0b\n\x03\x61rm\x18\x01 \x01(\x08\x12\r\n\x05\x66orce\x18\x02 \x01(\x08\x62\x06proto3')
)




_FLIGHTARMING = _descriptor.Descriptor(
  name='FlightArming',
  full_name='lynk.command.FlightArming',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arm', full_name='lynk.command.FlightArming.arm', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force', full_name='lynk.command.FlightArming.force', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['FlightArming'] = _FLIGHTARMING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlightArming = _reflection.GeneratedProtocolMessageType('FlightArming', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHTARMING,
  __module__ = 'msg.command.flight_arming_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.FlightArming)
  ))
_sym_db.RegisterMessage(FlightArming)


# @@protoc_insertion_point(module_scope)
