# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/swarm_formation_execute.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/swarm_formation_execute.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)msg/command/swarm_formation_execute.proto\x12\x0clynk.command\x1a\x0cnanopb.proto\"z\n\x15SwarmFormationExecute\x12\x11\n\tleader_id\x18\x01 \x01(\r\x12\x1d\n\x0e\x66ormation_type\x18\x02 \x01(\tB\x05\x92?\x02\x08 \x12\x16\n\x0espacing_offset\x18\x03 \x01(\x01\x12\x17\n\x0f\x61ltitude_offset\x18\x04 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_SWARMFORMATIONEXECUTE = _descriptor.Descriptor(
  name='SwarmFormationExecute',
  full_name='lynk.command.SwarmFormationExecute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leader_id', full_name='lynk.command.SwarmFormationExecute.leader_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='formation_type', full_name='lynk.command.SwarmFormationExecute.formation_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\010 '), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spacing_offset', full_name='lynk.command.SwarmFormationExecute.spacing_offset', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude_offset', full_name='lynk.command.SwarmFormationExecute.altitude_offset', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=195,
)

DESCRIPTOR.message_types_by_name['SwarmFormationExecute'] = _SWARMFORMATIONEXECUTE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwarmFormationExecute = _reflection.GeneratedProtocolMessageType('SwarmFormationExecute', (_message.Message,), dict(
  DESCRIPTOR = _SWARMFORMATIONEXECUTE,
  __module__ = 'msg.command.swarm_formation_execute_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.SwarmFormationExecute)
  ))
_sym_db.RegisterMessage(SwarmFormationExecute)


_SWARMFORMATIONEXECUTE.fields_by_name['formation_type']._options = None
# @@protoc_insertion_point(module_scope)
