# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/system_set_vehicle_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/system_set_vehicle_id.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'msg/command/system_set_vehicle_id.proto\x12\x0clynk.command\"(\n\x12SystemSetVehicleId\x12\x12\n\nvehicle_id\x18\x01 \x01(\rb\x06proto3')
)




_SYSTEMSETVEHICLEID = _descriptor.Descriptor(
  name='SystemSetVehicleId',
  full_name='lynk.command.SystemSetVehicleId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehicle_id', full_name='lynk.command.SystemSetVehicleId.vehicle_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['SystemSetVehicleId'] = _SYSTEMSETVEHICLEID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemSetVehicleId = _reflection.GeneratedProtocolMessageType('SystemSetVehicleId', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMSETVEHICLEID,
  __module__ = 'msg.command.system_set_vehicle_id_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.SystemSetVehicleId)
  ))
_sym_db.RegisterMessage(SystemSetVehicleId)


# @@protoc_insertion_point(module_scope)
