# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/system_set_team_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/system_set_team_id.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$msg/command/system_set_team_id.proto\x12\x0clynk.command\"\"\n\x0fSystemSetTeamId\x12\x0f\n\x07team_id\x18\x01 \x01(\rb\x06proto3')
)




_SYSTEMSETTEAMID = _descriptor.Descriptor(
  name='SystemSetTeamId',
  full_name='lynk.command.SystemSetTeamId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_id', full_name='lynk.command.SystemSetTeamId.team_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['SystemSetTeamId'] = _SYSTEMSETTEAMID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemSetTeamId = _reflection.GeneratedProtocolMessageType('SystemSetTeamId', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMSETTEAMID,
  __module__ = 'msg.command.system_set_team_id_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.SystemSetTeamId)
  ))
_sym_db.RegisterMessage(SystemSetTeamId)


# @@protoc_insertion_point(module_scope)
