# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/command/system_reboot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/command/system_reboot.proto',
  package='lynk.command',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fmsg/command/system_reboot.proto\x12\x0clynk.command\"\x0e\n\x0cSystemRebootb\x06proto3')
)




_SYSTEMREBOOT = _descriptor.Descriptor(
  name='SystemReboot',
  full_name='lynk.command.SystemReboot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['SystemReboot'] = _SYSTEMREBOOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemReboot = _reflection.GeneratedProtocolMessageType('SystemReboot', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMREBOOT,
  __module__ = 'msg.command.system_reboot_pb2'
  # @@protoc_insertion_point(class_scope:lynk.command.SystemReboot)
  ))
_sym_db.RegisterMessage(SystemReboot)


# @@protoc_insertion_point(module_scope)
