# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/battery_low.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/battery_low.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bmsg/event/battery_low.proto\x12\nlynk.event\"Y\n\nBatteryLow\x12\x0f\n\x07voltage\x18\x01 \x01(\x02\x12\x19\n\x11remaining_percent\x18\x02 \x01(\r\x12\x1f\n\x17\x65stimated_flight_time_s\x18\x03 \x01(\x02\x62\x06proto3')
)




_BATTERYLOW = _descriptor.Descriptor(
  name='BatteryLow',
  full_name='lynk.event.BatteryLow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='voltage', full_name='lynk.event.BatteryLow.voltage', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remaining_percent', full_name='lynk.event.BatteryLow.remaining_percent', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimated_flight_time_s', full_name='lynk.event.BatteryLow.estimated_flight_time_s', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['BatteryLow'] = _BATTERYLOW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BatteryLow = _reflection.GeneratedProtocolMessageType('BatteryLow', (_message.Message,), dict(
  DESCRIPTOR = _BATTERYLOW,
  __module__ = 'msg.event.battery_low_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.BatteryLow)
  ))
_sym_db.RegisterMessage(BatteryLow)


# @@protoc_insertion_point(module_scope)
