# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/collision_risk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/collision_risk.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1emsg/event/collision_risk.proto\x12\nlynk.event\"z\n\rCollisionRisk\x12\x19\n\x11target_vehicle_id\x18\x01 \x01(\r\x12\x12\n\ndistance_m\x18\x02 \x01(\x02\x12\x1d\n\x15relative_velocity_mps\x18\x03 \x01(\x02\x12\x1b\n\x13time_to_collision_s\x18\x04 \x01(\x02\x62\x06proto3')
)




_COLLISIONRISK = _descriptor.Descriptor(
  name='CollisionRisk',
  full_name='lynk.event.CollisionRisk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_vehicle_id', full_name='lynk.event.CollisionRisk.target_vehicle_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance_m', full_name='lynk.event.CollisionRisk.distance_m', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relative_velocity_mps', full_name='lynk.event.CollisionRisk.relative_velocity_mps', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_to_collision_s', full_name='lynk.event.CollisionRisk.time_to_collision_s', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=168,
)

DESCRIPTOR.message_types_by_name['CollisionRisk'] = _COLLISIONRISK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CollisionRisk = _reflection.GeneratedProtocolMessageType('CollisionRisk', (_message.Message,), dict(
  DESCRIPTOR = _COLLISIONRISK,
  __module__ = 'msg.event.collision_risk_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.CollisionRisk)
  ))
_sym_db.RegisterMessage(CollisionRisk)


# @@protoc_insertion_point(module_scope)
