# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/command_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.event import event_enums_pb2 as msg_dot_event_dot_event__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/command_status.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1emsg/event/command_status.proto\x12\nlynk.event\x1a\x1bmsg/event/event_enums.proto\"\x9b\x01\n\rCommandStatus\x12\x14\n\x0c\x63ommand_name\x18\x01 \x01(\t\x12\x15\n\rcommand_tx_id\x18\x02 \x01(\t\x12\x32\n\x06status\x18\x03 \x01(\x0e\x32\".lynk.event.CommandExecutionStatus\x12\x12\n\nerror_code\x18\x04 \x01(\r\x12\x15\n\rerror_message\x18\x05 \x01(\tb\x06proto3')
  ,
  dependencies=[msg_dot_event_dot_event__enums__pb2.DESCRIPTOR,])




_COMMANDSTATUS = _descriptor.Descriptor(
  name='CommandStatus',
  full_name='lynk.event.CommandStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_name', full_name='lynk.event.CommandStatus.command_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command_tx_id', full_name='lynk.event.CommandStatus.command_tx_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='lynk.event.CommandStatus.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='lynk.event.CommandStatus.error_code', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='lynk.event.CommandStatus.error_message', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=231,
)

_COMMANDSTATUS.fields_by_name['status'].enum_type = msg_dot_event_dot_event__enums__pb2._COMMANDEXECUTIONSTATUS
DESCRIPTOR.message_types_by_name['CommandStatus'] = _COMMANDSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandStatus = _reflection.GeneratedProtocolMessageType('CommandStatus', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDSTATUS,
  __module__ = 'msg.event.command_status_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.CommandStatus)
  ))
_sym_db.RegisterMessage(CommandStatus)


# @@protoc_insertion_point(module_scope)
