# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/crash_detected.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.event import event_enums_pb2 as msg_dot_event_dot_event__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/crash_detected.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1emsg/event/crash_detected.proto\x12\nlynk.event\x1a\x1bmsg/event/event_enums.proto\"\xc0\x01\n\rCrashDetected\x12\x1a\n\x12\x63rashed_vehicle_id\x18\x01 \x01(\r\x12\x1b\n\x13\x65stimated_crash_lat\x18\x02 \x01(\x02\x12\x1b\n\x13\x65stimated_crash_lon\x18\x03 \x01(\x02\x12:\n\x10\x64\x65tection_method\x18\x04 \x01(\x0e\x32 .lynk.event.CrashDetectionMethod\x12\x1d\n\x15vertical_velocity_mps\x18\x05 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[msg_dot_event_dot_event__enums__pb2.DESCRIPTOR,])




_CRASHDETECTED = _descriptor.Descriptor(
  name='CrashDetected',
  full_name='lynk.event.CrashDetected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='crashed_vehicle_id', full_name='lynk.event.CrashDetected.crashed_vehicle_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimated_crash_lat', full_name='lynk.event.CrashDetected.estimated_crash_lat', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimated_crash_lon', full_name='lynk.event.CrashDetected.estimated_crash_lon', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detection_method', full_name='lynk.event.CrashDetected.detection_method', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertical_velocity_mps', full_name='lynk.event.CrashDetected.vertical_velocity_mps', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=268,
)

_CRASHDETECTED.fields_by_name['detection_method'].enum_type = msg_dot_event_dot_event__enums__pb2._CRASHDETECTIONMETHOD
DESCRIPTOR.message_types_by_name['CrashDetected'] = _CRASHDETECTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrashDetected = _reflection.GeneratedProtocolMessageType('CrashDetected', (_message.Message,), dict(
  DESCRIPTOR = _CRASHDETECTED,
  __module__ = 'msg.event.crash_detected_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.CrashDetected)
  ))
_sym_db.RegisterMessage(CrashDetected)


# @@protoc_insertion_point(module_scope)
