# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/custom_event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/custom_event.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cmsg/event/custom_event.proto\x12\nlynk.event\"\xb2\x01\n\x0b\x43ustomEvent\x12\x12\n\nevent_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x37\n\x08metadata\x18\x03 \x03(\x0b\x32%.lynk.event.CustomEvent.MetadataEntry\x12\x10\n\x08raw_data\x18\x04 \x01(\x0c\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)




_CUSTOMEVENT_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='lynk.event.CustomEvent.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='lynk.event.CustomEvent.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='lynk.event.CustomEvent.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=223,
)

_CUSTOMEVENT = _descriptor.Descriptor(
  name='CustomEvent',
  full_name='lynk.event.CustomEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_name', full_name='lynk.event.CustomEvent.event_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='lynk.event.CustomEvent.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='lynk.event.CustomEvent.metadata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_data', full_name='lynk.event.CustomEvent.raw_data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CUSTOMEVENT_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=223,
)

_CUSTOMEVENT_METADATAENTRY.containing_type = _CUSTOMEVENT
_CUSTOMEVENT.fields_by_name['metadata'].message_type = _CUSTOMEVENT_METADATAENTRY
DESCRIPTOR.message_types_by_name['CustomEvent'] = _CUSTOMEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomEvent = _reflection.GeneratedProtocolMessageType('CustomEvent', (_message.Message,), dict(

  MetadataEntry = _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), dict(
    DESCRIPTOR = _CUSTOMEVENT_METADATAENTRY,
    __module__ = 'msg.event.custom_event_pb2'
    # @@protoc_insertion_point(class_scope:lynk.event.CustomEvent.MetadataEntry)
    ))
  ,
  DESCRIPTOR = _CUSTOMEVENT,
  __module__ = 'msg.event.custom_event_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.CustomEvent)
  ))
_sym_db.RegisterMessage(CustomEvent)
_sym_db.RegisterMessage(CustomEvent.MetadataEntry)


_CUSTOMEVENT_METADATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
