# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/emergency_crash.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.event import event_enums_pb2 as msg_dot_event_dot_event__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/emergency_crash.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fmsg/event/emergency_crash.proto\x12\nlynk.event\x1a\x1bmsg/event/event_enums.proto\"z\n\x0e\x45mergencyCrash\x12\'\n\x06reason\x18\x01 \x01(\x0e\x32\x17.lynk.event.CrashReason\x12\x12\n\naltitude_m\x18\x02 \x01(\x02\x12\x17\n\x0f\x62\x61ttery_percent\x18\x03 \x01(\r\x12\x12\n\nlast_error\x18\x04 \x01(\tb\x06proto3')
  ,
  dependencies=[msg_dot_event_dot_event__enums__pb2.DESCRIPTOR,])




_EMERGENCYCRASH = _descriptor.Descriptor(
  name='EmergencyCrash',
  full_name='lynk.event.EmergencyCrash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='lynk.event.EmergencyCrash.reason', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude_m', full_name='lynk.event.EmergencyCrash.altitude_m', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery_percent', full_name='lynk.event.EmergencyCrash.battery_percent', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_error', full_name='lynk.event.EmergencyCrash.last_error', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=198,
)

_EMERGENCYCRASH.fields_by_name['reason'].enum_type = msg_dot_event_dot_event__enums__pb2._CRASHREASON
DESCRIPTOR.message_types_by_name['EmergencyCrash'] = _EMERGENCYCRASH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmergencyCrash = _reflection.GeneratedProtocolMessageType('EmergencyCrash', (_message.Message,), dict(
  DESCRIPTOR = _EMERGENCYCRASH,
  __module__ = 'msg.event.emergency_crash_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.EmergencyCrash)
  ))
_sym_db.RegisterMessage(EmergencyCrash)


# @@protoc_insertion_point(module_scope)
