# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/failsafe_triggered.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.event import event_enums_pb2 as msg_dot_event_dot_event__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/failsafe_triggered.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"msg/event/failsafe_triggered.proto\x12\nlynk.event\x1a\x1bmsg/event/event_enums.proto\"k\n\x11\x46\x61ilsafeTriggered\x12*\n\x06reason\x18\x01 \x01(\x0e\x32\x1a.lynk.event.FailsafeReason\x12*\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x1a.lynk.event.FailsafeActionb\x06proto3')
  ,
  dependencies=[msg_dot_event_dot_event__enums__pb2.DESCRIPTOR,])




_FAILSAFETRIGGERED = _descriptor.Descriptor(
  name='FailsafeTriggered',
  full_name='lynk.event.FailsafeTriggered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='lynk.event.FailsafeTriggered.reason', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='lynk.event.FailsafeTriggered.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=186,
)

_FAILSAFETRIGGERED.fields_by_name['reason'].enum_type = msg_dot_event_dot_event__enums__pb2._FAILSAFEREASON
_FAILSAFETRIGGERED.fields_by_name['action'].enum_type = msg_dot_event_dot_event__enums__pb2._FAILSAFEACTION
DESCRIPTOR.message_types_by_name['FailsafeTriggered'] = _FAILSAFETRIGGERED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FailsafeTriggered = _reflection.GeneratedProtocolMessageType('FailsafeTriggered', (_message.Message,), dict(
  DESCRIPTOR = _FAILSAFETRIGGERED,
  __module__ = 'msg.event.failsafe_triggered_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.FailsafeTriggered)
  ))
_sym_db.RegisterMessage(FailsafeTriggered)


# @@protoc_insertion_point(module_scope)
