# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/formation_broken.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.event import event_enums_pb2 as msg_dot_event_dot_event__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/formation_broken.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n msg/event/formation_broken.proto\x12\nlynk.event\x1a\x1bmsg/event/event_enums.proto\"\x83\x01\n\x0f\x46ormationBroken\x12\x1a\n\x12missing_vehicle_id\x18\x01 \x01(\r\x12\x31\n\x06reason\x18\x02 \x01(\x0e\x32!.lynk.event.FormationBrokenReason\x12!\n\x19time_since_last_contact_s\x18\x03 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[msg_dot_event_dot_event__enums__pb2.DESCRIPTOR,])




_FORMATIONBROKEN = _descriptor.Descriptor(
  name='FormationBroken',
  full_name='lynk.event.FormationBroken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='missing_vehicle_id', full_name='lynk.event.FormationBroken.missing_vehicle_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='lynk.event.FormationBroken.reason', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_since_last_contact_s', full_name='lynk.event.FormationBroken.time_since_last_contact_s', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=209,
)

_FORMATIONBROKEN.fields_by_name['reason'].enum_type = msg_dot_event_dot_event__enums__pb2._FORMATIONBROKENREASON
DESCRIPTOR.message_types_by_name['FormationBroken'] = _FORMATIONBROKEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FormationBroken = _reflection.GeneratedProtocolMessageType('FormationBroken', (_message.Message,), dict(
  DESCRIPTOR = _FORMATIONBROKEN,
  __module__ = 'msg.event.formation_broken_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.FormationBroken)
  ))
_sym_db.RegisterMessage(FormationBroken)


# @@protoc_insertion_point(module_scope)
