# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/gps_degraded.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.event import event_enums_pb2 as msg_dot_event_dot_event__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/gps_degraded.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cmsg/event/gps_degraded.proto\x12\nlynk.event\x1a\x1bmsg/event/event_enums.proto\"^\n\x0bGpsDegraded\x12\x12\n\nsatellites\x18\x01 \x01(\r\x12\x0c\n\x04hdop\x18\x02 \x01(\x02\x12-\n\x06reason\x18\x03 \x01(\x0e\x32\x1d.lynk.event.GpsDegradedReasonb\x06proto3')
  ,
  dependencies=[msg_dot_event_dot_event__enums__pb2.DESCRIPTOR,])




_GPSDEGRADED = _descriptor.Descriptor(
  name='GpsDegraded',
  full_name='lynk.event.GpsDegraded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='satellites', full_name='lynk.event.GpsDegraded.satellites', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hdop', full_name='lynk.event.GpsDegraded.hdop', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='lynk.event.GpsDegraded.reason', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=167,
)

_GPSDEGRADED.fields_by_name['reason'].enum_type = msg_dot_event_dot_event__enums__pb2._GPSDEGRADEDREASON
DESCRIPTOR.message_types_by_name['GpsDegraded'] = _GPSDEGRADED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GpsDegraded = _reflection.GeneratedProtocolMessageType('GpsDegraded', (_message.Message,), dict(
  DESCRIPTOR = _GPSDEGRADED,
  __module__ = 'msg.event.gps_degraded_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.GpsDegraded)
  ))
_sym_db.RegisterMessage(GpsDegraded)


# @@protoc_insertion_point(module_scope)
