# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/mission_waypoint_reached.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/mission_waypoint_reached.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(msg/event/mission_waypoint_reached.proto\x12\nlynk.event\"c\n\x16MissionWaypointReached\x12\x16\n\x0ewaypoint_index\x18\x01 \x01(\r\x12\x17\n\x0ftotal_waypoints\x18\x02 \x01(\r\x12\x18\n\x10\x64istance_error_m\x18\x03 \x01(\x02\x62\x06proto3')
)




_MISSIONWAYPOINTREACHED = _descriptor.Descriptor(
  name='MissionWaypointReached',
  full_name='lynk.event.MissionWaypointReached',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='waypoint_index', full_name='lynk.event.MissionWaypointReached.waypoint_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_waypoints', full_name='lynk.event.MissionWaypointReached.total_waypoints', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance_error_m', full_name='lynk.event.MissionWaypointReached.distance_error_m', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['MissionWaypointReached'] = _MISSIONWAYPOINTREACHED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MissionWaypointReached = _reflection.GeneratedProtocolMessageType('MissionWaypointReached', (_message.Message,), dict(
  DESCRIPTOR = _MISSIONWAYPOINTREACHED,
  __module__ = 'msg.event.mission_waypoint_reached_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.MissionWaypointReached)
  ))
_sym_db.RegisterMessage(MissionWaypointReached)


# @@protoc_insertion_point(module_scope)
