# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/mission_complete.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/mission_complete.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n msg/event/mission_complete.proto\x12\nlynk.event\"Z\n\x0fMissionComplete\x12\x17\n\x0ftotal_waypoints\x18\x01 \x01(\r\x12\x18\n\x10total_distance_m\x18\x02 \x01(\x02\x12\x14\n\x0ctotal_time_s\x18\x03 \x01(\x02\x62\x06proto3')
)




_MISSIONCOMPLETE = _descriptor.Descriptor(
  name='MissionComplete',
  full_name='lynk.event.MissionComplete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_waypoints', full_name='lynk.event.MissionComplete.total_waypoints', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_distance_m', full_name='lynk.event.MissionComplete.total_distance_m', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_time_s', full_name='lynk.event.MissionComplete.total_time_s', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['MissionComplete'] = _MISSIONCOMPLETE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MissionComplete = _reflection.GeneratedProtocolMessageType('MissionComplete', (_message.Message,), dict(
  DESCRIPTOR = _MISSIONCOMPLETE,
  __module__ = 'msg.event.mission_complete_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.MissionComplete)
  ))
_sym_db.RegisterMessage(MissionComplete)


# @@protoc_insertion_point(module_scope)
