# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/motor_failure.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.event import event_enums_pb2 as msg_dot_event_dot_event__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/motor_failure.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dmsg/event/motor_failure.proto\x12\nlynk.event\x1a\x1bmsg/event/event_enums.proto\"\x7f\n\x0cMotorFailure\x12\x10\n\x08motor_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63urrent_rpm\x18\x02 \x01(\r\x12\x14\n\x0c\x65xpected_rpm\x18\x03 \x01(\r\x12\x32\n\x0c\x66\x61ilure_type\x18\x04 \x01(\x0e\x32\x1c.lynk.event.MotorFailureTypeb\x06proto3')
  ,
  dependencies=[msg_dot_event_dot_event__enums__pb2.DESCRIPTOR,])




_MOTORFAILURE = _descriptor.Descriptor(
  name='MotorFailure',
  full_name='lynk.event.MotorFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_id', full_name='lynk.event.MotorFailure.motor_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_rpm', full_name='lynk.event.MotorFailure.current_rpm', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expected_rpm', full_name='lynk.event.MotorFailure.expected_rpm', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failure_type', full_name='lynk.event.MotorFailure.failure_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=201,
)

_MOTORFAILURE.fields_by_name['failure_type'].enum_type = msg_dot_event_dot_event__enums__pb2._MOTORFAILURETYPE
DESCRIPTOR.message_types_by_name['MotorFailure'] = _MOTORFAILURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotorFailure = _reflection.GeneratedProtocolMessageType('MotorFailure', (_message.Message,), dict(
  DESCRIPTOR = _MOTORFAILURE,
  __module__ = 'msg.event.motor_failure_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.MotorFailure)
  ))
_sym_db.RegisterMessage(MotorFailure)


# @@protoc_insertion_point(module_scope)
