# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/obstacle_detected.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.event import event_enums_pb2 as msg_dot_event_dot_event__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/obstacle_detected.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!msg/event/obstacle_detected.proto\x12\nlynk.event\x1a\x1bmsg/event/event_enums.proto\"l\n\x10ObstacleDetected\x12\x12\n\ndistance_m\x18\x01 \x01(\x02\x12\x13\n\x0b\x62\x65\x61ring_deg\x18\x02 \x01(\x02\x12/\n\robstacle_type\x18\x03 \x01(\x0e\x32\x18.lynk.event.ObstacleTypeb\x06proto3')
  ,
  dependencies=[msg_dot_event_dot_event__enums__pb2.DESCRIPTOR,])




_OBSTACLEDETECTED = _descriptor.Descriptor(
  name='ObstacleDetected',
  full_name='lynk.event.ObstacleDetected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance_m', full_name='lynk.event.ObstacleDetected.distance_m', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bearing_deg', full_name='lynk.event.ObstacleDetected.bearing_deg', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obstacle_type', full_name='lynk.event.ObstacleDetected.obstacle_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=186,
)

_OBSTACLEDETECTED.fields_by_name['obstacle_type'].enum_type = msg_dot_event_dot_event__enums__pb2._OBSTACLETYPE
DESCRIPTOR.message_types_by_name['ObstacleDetected'] = _OBSTACLEDETECTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObstacleDetected = _reflection.GeneratedProtocolMessageType('ObstacleDetected', (_message.Message,), dict(
  DESCRIPTOR = _OBSTACLEDETECTED,
  __module__ = 'msg.event.obstacle_detected_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.ObstacleDetected)
  ))
_sym_db.RegisterMessage(ObstacleDetected)


# @@protoc_insertion_point(module_scope)
