# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/target_detected.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/target_detected.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fmsg/event/target_detected.proto\x12\nlynk.event\"{\n\x0eTargetDetected\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x12\n\naltitude_m\x18\x03 \x01(\x01\x12\x13\n\x0b\x64\x65tected_at\x18\x04 \x01(\t\x12\x1b\n\x13\x64\x65tected_at_unix_ms\x18\x05 \x01(\x04\x62\x06proto3')
)




_TARGETDETECTED = _descriptor.Descriptor(
  name='TargetDetected',
  full_name='lynk.event.TargetDetected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='lynk.event.TargetDetected.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='lynk.event.TargetDetected.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude_m', full_name='lynk.event.TargetDetected.altitude_m', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detected_at', full_name='lynk.event.TargetDetected.detected_at', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detected_at_unix_ms', full_name='lynk.event.TargetDetected.detected_at_unix_ms', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['TargetDetected'] = _TARGETDETECTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TargetDetected = _reflection.GeneratedProtocolMessageType('TargetDetected', (_message.Message,), dict(
  DESCRIPTOR = _TARGETDETECTED,
  __module__ = 'msg.event.target_detected_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.TargetDetected)
  ))
_sym_db.RegisterMessage(TargetDetected)


# @@protoc_insertion_point(module_scope)
