# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg/event/vehicle_lost.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg/event/vehicle_lost.proto',
  package='lynk.event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cmsg/event/vehicle_lost.proto\x12\nlynk.event\"t\n\x0bVehicleLost\x12\x17\n\x0flost_vehicle_id\x18\x01 \x01(\r\x12\x16\n\x0elast_known_lat\x18\x02 \x01(\x02\x12\x16\n\x0elast_known_lon\x18\x03 \x01(\x02\x12\x1c\n\x14time_since_contact_s\x18\x04 \x01(\x02\x62\x06proto3')
)




_VEHICLELOST = _descriptor.Descriptor(
  name='VehicleLost',
  full_name='lynk.event.VehicleLost',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lost_vehicle_id', full_name='lynk.event.VehicleLost.lost_vehicle_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_known_lat', full_name='lynk.event.VehicleLost.last_known_lat', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_known_lon', full_name='lynk.event.VehicleLost.last_known_lon', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_since_contact_s', full_name='lynk.event.VehicleLost.time_since_contact_s', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['VehicleLost'] = _VEHICLELOST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VehicleLost = _reflection.GeneratedProtocolMessageType('VehicleLost', (_message.Message,), dict(
  DESCRIPTOR = _VEHICLELOST,
  __module__ = 'msg.event.vehicle_lost_pb2'
  # @@protoc_insertion_point(class_scope:lynk.event.VehicleLost)
  ))
_sym_db.RegisterMessage(VehicleLost)


# @@protoc_insertion_point(module_scope)
